#!/usr/bin/expect

set timeout 20
set username "9w032rvx"
set passwd "8^g%0316"

spawn git add *
spawn git commit -a -m "1"
spawn git push https://github.com/9w032rvx/9w032rvx.github.io.git master
expect {
    "*Username*" {
        set timeout 1000
        send "$username\r"

    }
    "*es/no)?*" {
        send "yes\r"

    }
    timeout {
        puts "connect is timeout"
        exit 3
    }
}


expect {
    "*Password*" {
        set timeout 1000
        send "$passwd\r"
        exp_continue
    }
    "*es/no)?*" {
        send "yes\r"
        exp_continue
    }
    timeout {
        puts "connect is timeout"
        exit 3
    }
}
